# Generated by Django 4.2.4 on 2023-08-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(default='default/defaultpicture.jpg', upload_to='profileImages'),
        ),
    ]
