# Generated by Django 4.2.4 on 2023-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFileManager',
            fields=[
                ('file_name', models.CharField(default='File', max_length=200)),
                ('file_description', models.TextField(default='This is a File', max_length=200)),
                ('file_type', models.CharField(choices=[('pdf', 'pdf'), ('image', 'image'), ('audio', 'audio'), ('video', 'video'), ('other', 'other')], max_length=20)),
                ('my_file', models.FileField(upload_to='all_files')),
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-file_upload_date',),
            },
        ),
    ]
