# Generated by Django 4.2.4 on 2023-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfilemanager',
            name='file_description',
            field=models.CharField(default='This is a File', max_length=200),
        ),
    ]
