# Generated by Django 4.2.4 on 2023-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_myfilemanager_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfilemanager',
            name='file_description',
            field=models.TextField(default='This is a File', max_length=200),
        ),
    ]
