# Generated by Django 4.2.4 on 2023-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_myfilemanager_downloadcount_myfilemanager_emailcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfilemanager',
            name='totalFileDownload',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
